"""L1 BLAS emitters: axpy, copy/swap, scal, dot, asum/nrm2 (reduce), iamax,
cabs1, rot, rotm, rotg, rotmg. Plus the emit_unsupported fallback stub."""
from .core import TypeInfo
from .scaffold import emit_main_linear

def emit_unsupported(name: str, ti: TypeInfo, shape: str) -> str:
    return f'''/* AUTOGENERATED — shape '{shape}' not yet implemented for {name}. */
#include <stdio.h>
int main(void) {{
    fprintf(stdout, "# {name}: not implemented (shape={shape})\\n");
    return 0;
}}
'''

# -- L1 ----------------------------------------------------------------------

def emit_axpy(name: str, ti: TypeInfo, is_c: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    p7 = ti.cmplx_lit_p7 if is_c else ti.real_lit_p7
    fill = 'PERF_FILL_C' if is_c else 'PERF_FILL_R'
    flops = '8.0 * (double)N' if is_c else '2.0 * (double)N'
    return f'''
BLAS_EXTERN void {name}_(const int *, const {T} *, const {T} *, const int *, {T} *, const int *);
BLAS_EXTERN void {name}_migrated_(const int *, const {T} *, const {T} *, const int *, {T} *, const int *);

static void run_{name}(int N, int iters, int warmup) {{
    int one = 1;
    {T} alpha = {p7};
    {T} *X  = PERF_ALLOC({T}, N);
    {T} *Y  = PERF_ALLOC({T}, N);
    {T} *Yi = PERF_ALLOC({T}, N);
    {fill}({T}, X,  N, 0);
    {fill}({T}, Yi, N, 1);
    PERF_RESET(Y, Yi, N, {T});

    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, &alpha, X, &one, Y, &one);          PERF_RESET(Y, Yi, N, {T});
        {name}_migrated_(&N, &alpha, X, &one, Y, &one); PERF_RESET(Y, Yi, N, {T});
    }}

    double t_subject, t_mg;
    PERF_RESET(Y, Yi, N, {T}); PERF_TIME(t_subject, iters, {name}_(&N, &alpha, X, &one, Y, &one));
    PERF_RESET(Y, Yi, N, {T}); PERF_TIME(t_mg,      iters, {name}_migrated_(&N, &alpha, X, &one, Y, &one));

    double flops = {flops};
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Yi);
}}

''' + emit_main_linear(f'run_{name}')


def emit_copy_swap(name: str, ti: TypeInfo, is_c: bool, swap: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    fill = 'PERF_FILL_C' if is_c else 'PERF_FILL_R'
    # swap=true reads+writes both X and Y; copy is X→Y only (X stays const).
    reset_iter = (f'PERF_RESET(X, Xi, N, {T}); PERF_RESET(Y, Yi, N, {T})'
                  if swap else f'PERF_RESET(Y, Yi, N, {T})')
    return f'''
BLAS_EXTERN void {name}_(const int *, {'const ' if not swap else ''}{T} *, const int *, {T} *, const int *);
BLAS_EXTERN void {name}_migrated_(const int *, {'const ' if not swap else ''}{T} *, const int *, {T} *, const int *);

static void run_{name}(int N, int iters, int warmup) {{
    int one = 1;
    {T} *X  = PERF_ALLOC({T}, N);
    {T} *Y  = PERF_ALLOC({T}, N);
    {T} *Xi = PERF_ALLOC({T}, N);
    {T} *Yi = PERF_ALLOC({T}, N);
    {fill}({T}, Xi, N, 0);
    {fill}({T}, Yi, N, 1);
    PERF_RESET(X, Xi, N, {T});
    PERF_RESET(Y, Yi, N, {T});
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, X, &one, Y, &one);          {reset_iter};
        {name}_migrated_(&N, X, &one, Y, &one); {reset_iter};
    }}
    /* Per-call timing (reset out of the timed window — see PERF_TIME_PER_CALL). */
    double t_subject, t_mg;
    PERF_TIME_PER_CALL(t_subject, iters, {reset_iter}, {name}_(&N, X, &one, Y, &one));
    PERF_TIME_PER_CALL(t_mg,      iters, {reset_iter}, {name}_migrated_(&N, X, &one, Y, &one));
    /* Bytes moved per call: copy=2N*sizeof(T), swap=4N*sizeof(T). Report
     * as "flops" for uniform formatting. */
    double flops = {'4.0' if swap else '2.0'} * (double)N * (double)sizeof({T});
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Xi); free(Yi);
}}

''' + emit_main_linear(f'run_{name}')


def emit_scal(name: str, ti: TypeInfo, is_c: bool, alpha_real: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    Ta = ti.real_T if alpha_real else T
    p7 = (ti.real_lit_p7 if alpha_real else
          (ti.cmplx_lit_p7 if is_c else ti.real_lit_p7))
    fill = 'PERF_FILL_C' if is_c else 'PERF_FILL_R'
    flops = '6.0 * (double)N' if is_c else '1.0 * (double)N'
    return f'''
BLAS_EXTERN void {name}_(const int *, const {Ta} *, {T} *, const int *);
BLAS_EXTERN void {name}_migrated_(const int *, const {Ta} *, {T} *, const int *);

static void run_{name}(int N, int iters, int warmup) {{
    int one = 1;
    {Ta} alpha = {p7};
    {T} *X  = PERF_ALLOC({T}, N);
    {T} *Xi = PERF_ALLOC({T}, N);
    {fill}({T}, Xi, N, 0);
    PERF_RESET(X, Xi, N, {T});
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, &alpha, X, &one);          PERF_RESET(X, Xi, N, {T});
        {name}_migrated_(&N, &alpha, X, &one); PERF_RESET(X, Xi, N, {T});
    }}
    /* Per-call timing (reset out of the timed window). */
    double t_subject, t_mg;
    PERF_TIME_PER_CALL(t_subject, iters, PERF_RESET(X, Xi, N, {T}), {name}_(&N, &alpha, X, &one));
    PERF_TIME_PER_CALL(t_mg,      iters, PERF_RESET(X, Xi, N, {T}), {name}_migrated_(&N, &alpha, X, &one));
    double flops = {flops};
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Xi);
}}

''' + emit_main_linear(f'run_{name}')

# -- L2 GEMV ------------------------------------------------------------------


def emit_dot(name: str, ti: TypeInfo, is_c: bool, conjugated: bool) -> str:
    """Real dot, complex dotu (conjugated=False), complex dotc (conjugated=True).

    All three return T by value at the C source level. The ABI handles
    the underlying call shape (register pair for kind10 _Complex long
    double; sret hidden pointer for >16-byte returns like _Complex
    __float128 and complex64x2). gcc and gfortran agree on the ABI for
    these types so a natural `T r = name_(...)` declaration matches.

    Anti-DCE: accumulate first-byte of `r` into a `volatile` sink across
    the timed loop. Without this gcc collapses the loop to one call.
    """
    T = ti.cmplx_T if is_c else ti.real_T
    fill = 'PERF_FILL_C' if is_c else 'PERF_FILL_R'
    flops = '8.0 * (double)N' if is_c else '2.0 * (double)N'
    sig = f'const int *, const {T} *, const int *, const {T} *, const int *'
    # Anti-DCE sink: take a few bytes of `r` and XOR into a volatile counter.
    return f'''
BLAS_EXTERN {T} {name}_({sig});
BLAS_EXTERN {T} {name}_migrated_({sig});

static volatile unsigned long perf_sink = 0;

static inline void sink_T(const {T} *p) {{
    /* extract first 8 bytes of T into volatile sink */
    unsigned long w;
    memcpy(&w, (const void *)p, sizeof(w));
    perf_sink ^= w;
}}

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {T} r;
    {T} *X = PERF_ALLOC({T}, N);
    {T} *Y = PERF_ALLOC({T}, N);
    {fill}({T}, X, N, 0);
    {fill}({T}, Y, N, 1);
    for (int r2 = 0; r2 < warmup; ++r2) {{
        r = {name}_(&N, X, &one, Y, &one);          sink_T(&r);
        r = {name}_migrated_(&N, X, &one, Y, &one); sink_T(&r);
    }}
    double t_subject, t_mg;
    PERF_TIME(t_subject, iters, r = {name}_(&N, X, &one, Y, &one); sink_T(&r));
    PERF_TIME(t_mg,      iters, r = {name}_migrated_(&N, X, &one, Y, &one); sink_T(&r));
    double flops = {flops};
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y);
}}

''' + emit_main_linear('run_one')


def emit_l1_reduce(name: str, ti: TypeInfo, is_c: bool,
                   flops_per_elem_real: float) -> str:
    """L1 vector→real-scalar reduction. Shared by asum and nrm2.

    asum/nrm2 have the same scan shape: walk one vector, fold into a real
    accumulator. Only the per-element flop count differs (asum=1, nrm2=2).
    Complex variants double the per-element count (one fold per Re and Im).
    """
    T = ti.cmplx_T if is_c else ti.real_T
    R = ti.real_T
    fill = 'PERF_FILL_C' if is_c else 'PERF_FILL_R'
    fpe = flops_per_elem_real * (2.0 if is_c else 1.0)
    flops = f'{fpe} * (double)N'
    sig = f'const int *, const {T} *, const int *'
    return f'''
BLAS_EXTERN {R} {name}_({sig});
BLAS_EXTERN {R} {name}_migrated_({sig});

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {R} r;
    {T} *X = PERF_ALLOC({T}, N);
    {fill}({T}, X, N, 0);
    for (int r2 = 0; r2 < warmup; ++r2) {{
        r = {name}_(&N, X, &one);
        r = {name}_migrated_(&N, X, &one);
    }}
    double t_subject, t_mg;
    PERF_TIME(t_subject, iters, r = {name}_(&N, X, &one));
    PERF_TIME(t_mg,      iters, r = {name}_migrated_(&N, X, &one));
    double flops = {flops};
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    if ((double)(*((double*)&r)) == -123e30) {{ free(X); return; }}
    free(X);
}}

''' + emit_main_linear('run_one')

def emit_iamax(name: str, ti: TypeInfo, is_c: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    fill = 'PERF_FILL_C' if is_c else 'PERF_FILL_R'
    flops = '2.0 * (double)N' if is_c else '1.0 * (double)N'
    return f'''
BLAS_EXTERN int {name}_(const int *, const {T} *, const int *);
BLAS_EXTERN int {name}_migrated_(const int *, const {T} *, const int *);

static void run_one(int N, int iters, int warmup) {{
    int one = 1, r = 0;
    {T} *X = PERF_ALLOC({T}, N);
    {fill}({T}, X, N, 0);
    for (int r2 = 0; r2 < warmup; ++r2) {{
        r ^= {name}_(&N, X, &one);
        r ^= {name}_migrated_(&N, X, &one);
    }}
    double t_subject, t_mg;
    PERF_TIME(t_subject, iters, r ^= {name}_(&N, X, &one));
    PERF_TIME(t_mg,      iters, r ^= {name}_migrated_(&N, X, &one));
    double flops = {flops};
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    if (r == -123) {{ free(X); return; }}
    free(X);
}}

''' + emit_main_linear('run_one')

# -- L2 symv/hemv (UPLO, N) --------------------------------------------------


def emit_rot(name: str, ti: TypeInfo, is_c: bool, real_cs: bool) -> str:
    """rot: x, y get rotated by (c, s). real_cs=True means c, s are real
    even when X, Y are complex (yerot/xqrot/wmrot)."""
    T = ti.cmplx_T if is_c else ti.real_T
    Tcs = ti.real_T if real_cs else T
    p7 = ti.real_lit_p7 if real_cs else (ti.cmplx_lit_p7 if is_c else ti.real_lit_p7)
    p3 = ti.real_lit_p3 if real_cs else (ti.cmplx_lit_p3 if is_c else ti.real_lit_p3)
    fill = 'PERF_FILL_C' if is_c else 'PERF_FILL_R'
    flops = '12.0 * (double)N' if is_c else '6.0 * (double)N'
    reset_iter = f'PERF_RESET(X, Xi, N, {T}); PERF_RESET(Y, Yi, N, {T})'
    return f'''
BLAS_EXTERN void {name}_(const int *, {T} *, const int *, {T} *, const int *,
    const {Tcs} *, const {Tcs} *);
BLAS_EXTERN void {name}_migrated_(const int *, {T} *, const int *, {T} *, const int *,
    const {Tcs} *, const {Tcs} *);

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {Tcs} c_ = {p7}, s_ = {p3};
    {T} *X  = PERF_ALLOC({T}, N);
    {T} *Y  = PERF_ALLOC({T}, N);
    {T} *Xi = PERF_ALLOC({T}, N);
    {T} *Yi = PERF_ALLOC({T}, N);
    {fill}({T}, Xi, N, 0);
    {fill}({T}, Yi, N, 1);
    PERF_RESET(X, Xi, N, {T});
    PERF_RESET(Y, Yi, N, {T});
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, X, &one, Y, &one, &c_, &s_);          {reset_iter};
        {name}_migrated_(&N, X, &one, Y, &one, &c_, &s_); {reset_iter};
    }}
    /* Per-call timing (reset out of the timed window). */
    double t_subject, t_mg;
    PERF_TIME_PER_CALL(t_subject, iters, {reset_iter}, {name}_(&N, X, &one, Y, &one, &c_, &s_));
    PERF_TIME_PER_CALL(t_mg,      iters, {reset_iter}, {name}_migrated_(&N, X, &one, Y, &one, &c_, &s_));
    double flops = {flops};
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Xi); free(Yi);
}}

''' + emit_main_linear('run_one')

# -- L1 rotm: modified Givens apply ------------------------------------------


def emit_rotm(name: str, ti: TypeInfo) -> str:
    """rotm: real-only. PARAM(5)."""
    T = ti.real_T
    p7 = ti.real_lit_p7
    reset_iter = f'PERF_RESET(X, Xi, N, {T}); PERF_RESET(Y, Yi, N, {T})'
    return f'''
BLAS_EXTERN void {name}_(const int *, {T} *, const int *, {T} *, const int *,
    const {T} *);
BLAS_EXTERN void {name}_migrated_(const int *, {T} *, const int *, {T} *, const int *,
    const {T} *);

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {T} PARAM[5] = {{ {p7}, {p7}, {p7}, {p7}, {p7} }};
    PARAM[0] = Tr_from_d(-1.0); /* hflag=-1 → full matrix path */
    {T} *X  = PERF_ALLOC({T}, N);
    {T} *Y  = PERF_ALLOC({T}, N);
    {T} *Xi = PERF_ALLOC({T}, N);
    {T} *Yi = PERF_ALLOC({T}, N);
    PERF_FILL_R({T}, Xi, N, 0);
    PERF_FILL_R({T}, Yi, N, 1);
    PERF_RESET(X, Xi, N, {T});
    PERF_RESET(Y, Yi, N, {T});
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, X, &one, Y, &one, PARAM);          {reset_iter};
        {name}_migrated_(&N, X, &one, Y, &one, PARAM); {reset_iter};
    }}
    /* Per-call timing (reset out of the timed window). */
    double t_subject, t_mg;
    PERF_TIME_PER_CALL(t_subject, iters, {reset_iter}, {name}_(&N, X, &one, Y, &one, PARAM));
    PERF_TIME_PER_CALL(t_mg,      iters, {reset_iter}, {name}_migrated_(&N, X, &one, Y, &one, PARAM));
    double flops = 4.0 * (double)N;
    PERF_EMIT("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Xi); free(Yi);
}}

''' + emit_main_linear('run_one')

# -- L1 rotg / rotmg: scalar-only generators. Bench loop length is the
# effective N; we measure per-call latency.


def emit_cabs1(name: str, ti: TypeInfo) -> str:
    """cabs1: scalar |Re(z)| + |Im(z)| (complex in, real out). No N — looped
    single-call shape like rotg; flops is a per-call proxy."""
    C = ti.cmplx_T
    R = ti.real_T
    return f'''
BLAS_EXTERN {R} {name}_(const {C} *);
BLAS_EXTERN {R} {name}_migrated_(const {C} *);

static void run_one(int iters, int warmup) {{
    {C} Z = {ti.cmplx_lit_p7};
    {R} acc = Tr_from_d(0.0);
    for (int r = 0; r < warmup; ++r) {{
        acc += {name}_(&Z);
        acc += {name}_migrated_(&Z);
    }}
    double t_subject, t_mg;
    PERF_TIME(t_subject, iters, acc += {name}_(&Z));
    PERF_TIME(t_mg,      iters, acc += {name}_migrated_(&Z));
    /* per-call proxy: 2 abs + 1 add */
    double flops = 3.0;
    PERF_EMIT("{name}", "-", iters, iters, flops, t_subject, t_mg);
    if ((double)(*((double*)&acc)) == -123e30) return;
}}

int main(void) {{
    int iters  = perf_env_int("BLAS_PERF_ITERS", 100000);
    int warmup = perf_env_int("BLAS_PERF_WARMUP", 1000);
    perf_print_header();
    run_one(iters, warmup);
    return 0;
}}
'''


def emit_rotg(name: str, ti: TypeInfo, is_c: bool) -> str:
    """rotg: real takes 4 scalar args; complex takes 4 scalars (C is real)."""
    Ta = ti.cmplx_T if is_c else ti.real_T
    Tc = ti.real_T  # c is always real
    Ts = Ta         # s matches A's type
    p7 = ti.cmplx_lit_p7 if is_c else ti.real_lit_p7
    return f'''
BLAS_EXTERN void {name}_({Ta} *, {Ta} *, {Tc} *, {Ts} *);
BLAS_EXTERN void {name}_migrated_({Ta} *, {Ta} *, {Tc} *, {Ts} *);

static void run_one(int iters, int warmup) {{
    {Ta} A = {p7}, B = {p7};
    {Tc} C = Tr_from_d(0.0);
    {Ts} S = {('Tc_from_d(0.0)' if is_c else 'Tr_from_d(0.0)')};
    /* per call: regenerate fresh A, B inputs */
    for (int r = 0; r < warmup; ++r) {{
        {Ta} a = A, b = B; {name}_(&a, &b, &C, &S);
        a = A; b = B; {name}_migrated_(&a, &b, &C, &S);
    }}
    double t_subject, t_mg;
    PERF_TIME(t_subject, iters, {Ta} a = A, b = B; {name}_(&a, &b, &C, &S));
    PERF_TIME(t_mg,      iters, {Ta} a = A, b = B; {name}_migrated_(&a, &b, &C, &S));
    /* report time per call as "flops" abuse: per-call flop count ~10. */
    double flops = 10.0;
    PERF_EMIT("{name}", "-", iters, iters, flops, t_subject, t_mg);
}}

int main(void) {{
    int iters  = perf_env_int("BLAS_PERF_ITERS", 100000);
    int warmup = perf_env_int("BLAS_PERF_WARMUP", 1000);
    perf_print_header();
    run_one(iters, warmup);
    return 0;
}}
'''


def emit_rotmg(name: str, ti: TypeInfo) -> str:
    T = ti.real_T
    p7 = ti.real_lit_p7
    return f'''
BLAS_EXTERN void {name}_({T} *, {T} *, {T} *, const {T} *, {T} *);
BLAS_EXTERN void {name}_migrated_({T} *, {T} *, {T} *, const {T} *, {T} *);

static void run_one(int iters, int warmup) {{
    {T} D1 = {p7}, D2 = {p7}, X1 = {p7}, Y1 = {p7};
    {T} PARAM[5];
    for (int r = 0; r < warmup; ++r) {{
        {T} d1 = D1, d2 = D2, x1 = X1;
        {name}_(&d1, &d2, &x1, &Y1, PARAM);
        d1 = D1; d2 = D2; x1 = X1;
        {name}_migrated_(&d1, &d2, &x1, &Y1, PARAM);
    }}
    double t_subject, t_mg;
    PERF_TIME(t_subject, iters, {T} d1 = D1, d2 = D2, x1 = X1; {name}_(&d1, &d2, &x1, &Y1, PARAM));
    PERF_TIME(t_mg,      iters, {T} d1 = D1, d2 = D2, x1 = X1; {name}_migrated_(&d1, &d2, &x1, &Y1, PARAM));
    double flops = 20.0;
    PERF_EMIT("{name}", "-", iters, iters, flops, t_subject, t_mg);
}}

int main(void) {{
    int iters  = perf_env_int("BLAS_PERF_ITERS", 100000);
    int warmup = perf_env_int("BLAS_PERF_WARMUP", 1000);
    perf_print_header();
    run_one(iters, warmup);
    return 0;
}}
'''

