"""L1 BLAS emitters: axpy, copy/swap, scal, dot, asum/nrm2 (reduce), iamax,
cabs1, rot, rotm, rotg, rotmg. Plus the emit_unsupported fallback stub."""
from .core import TypeInfo
from .scaffold import emit_main_linear

def emit_unsupported(name: str, ti: TypeInfo, shape: str) -> str:
    return f'''/* AUTOGENERATED — shape '{shape}' not yet implemented for {name}. */
#include <stdio.h>
int main(void) {{
    fprintf(stdout, "# {name}: not implemented (shape={shape})\\n");
    return 0;
}}
'''

# -- L1 ----------------------------------------------------------------------

def emit_axpy(name: str, ti: TypeInfo, is_c: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    p7 = ti.cmplx_lit_p7 if is_c else ti.real_lit_p7
    fill = ti.cmplx_fill if is_c else ti.real_fill
    flops = '8.0 * (double)N' if is_c else '2.0 * (double)N'
    return f'''
BLAS_EXTERN void {name}_(const int *, const {T} *, const {T} *, const int *, {T} *, const int *);
BLAS_EXTERN void {name}_migrated_(const int *, const {T} *, const {T} *, const int *, {T} *, const int *);

static void run_{name}(int N, int iters, int warmup) {{
    int one = 1;
    {T} alpha = {p7};
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Y = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Yi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int s = 0; s < 1; ++s) {{}}
    for (int i = 0; i < N; ++i) {{ int s = 0; X[i] = {fill}; }}
    for (int i = 0; i < N; ++i) {{ int s = 1; Yi[i] = {fill}; }}
    memcpy(Y, Yi, (size_t)N * sizeof({T}));

    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, &alpha, X, &one, Y, &one);
        memcpy(Y, Yi, (size_t)N * sizeof({T}));
        {name}_migrated_(&N, &alpha, X, &one, Y, &one);
        memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}

    memcpy(Y, Yi, (size_t)N * sizeof({T}));
    double t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {name}_(&N, &alpha, X, &one, Y, &one);
    double t1 = perf_now_s();
    double t_subject = (t1 - t0) / (iters ? iters : 1);

    memcpy(Y, Yi, (size_t)N * sizeof({T}));
    t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {name}_migrated_(&N, &alpha, X, &one, Y, &one);
    t1 = perf_now_s();
    double t_mg = (t1 - t0) / (iters ? iters : 1);

    double flops = {flops};
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Yi);
}}

''' + emit_main_linear(f'run_{name}')


def emit_copy_swap(name: str, ti: TypeInfo, is_c: bool, swap: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    fill = ti.cmplx_fill if is_c else ti.real_fill
    return f'''
BLAS_EXTERN void {name}_(const int *, {'const ' if not swap else ''}{T} *, const int *, {T} *, const int *);
BLAS_EXTERN void {name}_migrated_(const int *, {'const ' if not swap else ''}{T} *, const int *, {T} *, const int *);

static void run_{name}(int N, int iters, int warmup) {{
    int one = 1;
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Y = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Xi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Yi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int i = 0; i < N; ++i) {{ int s = 0; Xi[i] = {fill}; }}
    for (int i = 0; i < N; ++i) {{ int s = 1; Yi[i] = {fill}; }}
    memcpy(X, Xi, (size_t)N * sizeof({T}));
    memcpy(Y, Yi, (size_t)N * sizeof({T}));
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, X, &one, Y, &one);
        memcpy(X, Xi, (size_t)N * sizeof({T}));
        memcpy(Y, Yi, (size_t)N * sizeof({T}));
        {name}_migrated_(&N, X, &one, Y, &one);
        memcpy(X, Xi, (size_t)N * sizeof({T}));
        memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    /* Per-call kernel-only timing — keep the reset memcpy OUT of the
     * timed window so a single-threaded reset doesn't Amdahl-cap the
     * measured MT scaling at large N. */
    double t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_(&N, X, &one, Y, &one);
        double b = perf_now_s();
        t_sum += (b - a);
        {'memcpy(X, Xi, (size_t)N * sizeof(' + T + ')); ' if swap else ''}memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    double t_subject = t_sum / (iters ? iters : 1);

    t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_migrated_(&N, X, &one, Y, &one);
        double b = perf_now_s();
        t_sum += (b - a);
        {'memcpy(X, Xi, (size_t)N * sizeof(' + T + ')); ' if swap else ''}memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    double t_mg = t_sum / (iters ? iters : 1);
    /* Bytes moved per call: copy=2N*sizeof(T), swap=4N*sizeof(T). Report
     * as "flops" for uniform formatting. */
    double flops = {'4.0' if swap else '2.0'} * (double)N * (double)sizeof({T});
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Xi); free(Yi);
}}

''' + emit_main_linear(f'run_{name}')


def emit_scal(name: str, ti: TypeInfo, is_c: bool, alpha_real: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    Ta = ti.real_T if alpha_real else T
    p7 = (ti.real_lit_p7 if alpha_real else
          (ti.cmplx_lit_p7 if is_c else ti.real_lit_p7))
    fill = ti.cmplx_fill if is_c else ti.real_fill
    flops = '6.0 * (double)N' if is_c else '1.0 * (double)N'
    return f'''
BLAS_EXTERN void {name}_(const int *, const {Ta} *, {T} *, const int *);
BLAS_EXTERN void {name}_migrated_(const int *, const {Ta} *, {T} *, const int *);

static void run_{name}(int N, int iters, int warmup) {{
    int one = 1;
    {Ta} alpha = {p7};
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Xi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int i = 0; i < N; ++i) {{ int s = 0; Xi[i] = {fill}; }}
    memcpy(X, Xi, (size_t)N * sizeof({T}));
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, &alpha, X, &one);
        memcpy(X, Xi, (size_t)N * sizeof({T}));
        {name}_migrated_(&N, &alpha, X, &one);
        memcpy(X, Xi, (size_t)N * sizeof({T}));
    }}
    /* Per-call kernel-only timing — keep memcpy reset out of the
     * timed window so it doesn't Amdahl-mask MT scaling. */
    double t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_(&N, &alpha, X, &one);
        double b = perf_now_s();
        t_sum += (b - a);
        memcpy(X, Xi, (size_t)N * sizeof({T}));
    }}
    double t_subject = t_sum / (iters ? iters : 1);

    t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_migrated_(&N, &alpha, X, &one);
        double b = perf_now_s();
        t_sum += (b - a);
        memcpy(X, Xi, (size_t)N * sizeof({T}));
    }}
    double t_mg = t_sum / (iters ? iters : 1);
    double flops = {flops};
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Xi);
}}

''' + emit_main_linear(f'run_{name}')

# -- L2 GEMV ------------------------------------------------------------------


def emit_dot(name: str, ti: TypeInfo, is_c: bool, conjugated: bool) -> str:
    """Real dot, complex dotu (conjugated=False), complex dotc (conjugated=True).

    All three return T by value at the C source level. The ABI handles
    the underlying call shape (register pair for kind10 _Complex long
    double; sret hidden pointer for >16-byte returns like _Complex
    __float128 and complex64x2). gcc and gfortran agree on the ABI for
    these types so a natural `T r = name_(...)` declaration matches.

    Anti-DCE: accumulate first-byte of `r` into a `volatile` sink across
    the timed loop. Without this gcc collapses the loop to one call.
    """
    T = ti.cmplx_T if is_c else ti.real_T
    fill = ti.cmplx_fill if is_c else ti.real_fill
    flops = '8.0 * (double)N' if is_c else '2.0 * (double)N'
    sig = f'const int *, const {T} *, const int *, const {T} *, const int *'
    # Anti-DCE sink: take a few bytes of `r` and XOR into a volatile counter.
    return f'''
BLAS_EXTERN {T} {name}_({sig});
BLAS_EXTERN {T} {name}_migrated_({sig});

static volatile unsigned long perf_sink = 0;

static inline void sink_T(const {T} *p) {{
    /* extract first 8 bytes of T into volatile sink */
    unsigned long w;
    memcpy(&w, (const void *)p, sizeof(w));
    perf_sink ^= w;
}}

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {T} r;
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Y = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int i = 0; i < N; ++i) {{ int s = 0; X[i] = {fill}; }}
    for (int i = 0; i < N; ++i) {{ int s = 1; Y[i] = {fill}; }}
    for (int r2 = 0; r2 < warmup; ++r2) {{
        r = {name}_(&N, X, &one, Y, &one); sink_T(&r);
        r = {name}_migrated_(&N, X, &one, Y, &one); sink_T(&r);
    }}
    double t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {{
        r = {name}_(&N, X, &one, Y, &one);
        sink_T(&r);
    }}
    double t1 = perf_now_s();
    double t_subject = (t1 - t0) / (iters ? iters : 1);

    t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {{
        r = {name}_migrated_(&N, X, &one, Y, &one);
        sink_T(&r);
    }}
    t1 = perf_now_s();
    double t_mg = (t1 - t0) / (iters ? iters : 1);

    double flops = {flops};
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y);
}}

''' + emit_main_linear('run_one')


def emit_l1_reduce(name: str, ti: TypeInfo, is_c: bool,
                   flops_per_elem_real: float) -> str:
    """L1 vector→real-scalar reduction. Shared by asum and nrm2.

    asum/nrm2 have the same scan shape: walk one vector, fold into a real
    accumulator. Only the per-element flop count differs (asum=1, nrm2=2).
    Complex variants double the per-element count (one fold per Re and Im).
    """
    T = ti.cmplx_T if is_c else ti.real_T
    R = ti.real_T
    fill = ti.cmplx_fill if is_c else ti.real_fill
    fpe = flops_per_elem_real * (2.0 if is_c else 1.0)
    flops = f'{fpe} * (double)N'
    sig = f'const int *, const {T} *, const int *'
    return f'''
BLAS_EXTERN {R} {name}_({sig});
BLAS_EXTERN {R} {name}_migrated_({sig});

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {R} r;
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int i = 0; i < N; ++i) {{ int s = 0; X[i] = {fill}; }}
    for (int r2 = 0; r2 < warmup; ++r2) {{
        r = {name}_(&N, X, &one);
        r = {name}_migrated_(&N, X, &one);
    }}
    double t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) r = {name}_(&N, X, &one);
    double t1 = perf_now_s();
    double t_subject = (t1 - t0) / (iters ? iters : 1);
    t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) r = {name}_migrated_(&N, X, &one);
    t1 = perf_now_s();
    double t_mg = (t1 - t0) / (iters ? iters : 1);
    double flops = {flops};
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    if ((double)(*((double*)&r)) == -123e30) {{ free(X); return; }}
    free(X);
}}

''' + emit_main_linear('run_one')

def emit_iamax(name: str, ti: TypeInfo, is_c: bool) -> str:
    T = ti.cmplx_T if is_c else ti.real_T
    fill = ti.cmplx_fill if is_c else ti.real_fill
    flops = '2.0 * (double)N' if is_c else '1.0 * (double)N'
    return f'''
BLAS_EXTERN int {name}_(const int *, const {T} *, const int *);
BLAS_EXTERN int {name}_migrated_(const int *, const {T} *, const int *);

static void run_one(int N, int iters, int warmup) {{
    int one = 1, r = 0;
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int i = 0; i < N; ++i) {{ int s = 0; X[i] = {fill}; }}
    for (int r2 = 0; r2 < warmup; ++r2) {{
        r ^= {name}_(&N, X, &one);
        r ^= {name}_migrated_(&N, X, &one);
    }}
    double t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) r ^= {name}_(&N, X, &one);
    double t1 = perf_now_s();
    double t_subject = (t1 - t0) / (iters ? iters : 1);
    t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) r ^= {name}_migrated_(&N, X, &one);
    t1 = perf_now_s();
    double t_mg = (t1 - t0) / (iters ? iters : 1);
    double flops = {flops};
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    if (r == -123) {{ free(X); return; }}
    free(X);
}}

''' + emit_main_linear('run_one')

# -- L2 symv/hemv (UPLO, N) --------------------------------------------------


def emit_rot(name: str, ti: TypeInfo, is_c: bool, real_cs: bool) -> str:
    """rot: x, y get rotated by (c, s). real_cs=True means c, s are real
    even when X, Y are complex (yerot/xqrot/wmrot)."""
    T = ti.cmplx_T if is_c else ti.real_T
    Tcs = ti.real_T if real_cs else T
    p7 = ti.real_lit_p7 if real_cs else (ti.cmplx_lit_p7 if is_c else ti.real_lit_p7)
    p3 = ti.real_lit_p3 if real_cs else (ti.cmplx_lit_p3 if is_c else ti.real_lit_p3)
    fill = ti.cmplx_fill if is_c else ti.real_fill
    flops = '12.0 * (double)N' if is_c else '6.0 * (double)N'
    return f'''
BLAS_EXTERN void {name}_(const int *, {T} *, const int *, {T} *, const int *,
    const {Tcs} *, const {Tcs} *);
BLAS_EXTERN void {name}_migrated_(const int *, {T} *, const int *, {T} *, const int *,
    const {Tcs} *, const {Tcs} *);

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {Tcs} c_ = {p7}, s_ = {p3};
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Y = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Xi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Yi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int i = 0; i < N; ++i) {{ int s = 0; Xi[i] = {fill}; }}
    for (int i = 0; i < N; ++i) {{ int s = 1; Yi[i] = {fill}; }}
    memcpy(X, Xi, (size_t)N * sizeof({T}));
    memcpy(Y, Yi, (size_t)N * sizeof({T}));
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, X, &one, Y, &one, &c_, &s_);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
        {name}_migrated_(&N, X, &one, Y, &one, &c_, &s_);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    /* Per-call kernel-only timing — keep memcpy resets out of the
     * timed window so they don't Amdahl-mask MT scaling. */
    double t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_(&N, X, &one, Y, &one, &c_, &s_);
        double b = perf_now_s();
        t_sum += (b - a);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    double t_subject = t_sum / (iters ? iters : 1);

    t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_migrated_(&N, X, &one, Y, &one, &c_, &s_);
        double b = perf_now_s();
        t_sum += (b - a);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    double t_mg = t_sum / (iters ? iters : 1);
    double flops = {flops};
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Xi); free(Yi);
}}

''' + emit_main_linear('run_one')

# -- L1 rotm: modified Givens apply ------------------------------------------


def emit_rotm(name: str, ti: TypeInfo) -> str:
    """rotm: real-only. PARAM(5)."""
    T = ti.real_T
    p7 = ti.real_lit_p7
    fill = ti.real_fill
    return f'''
BLAS_EXTERN void {name}_(const int *, {T} *, const int *, {T} *, const int *,
    const {T} *);
BLAS_EXTERN void {name}_migrated_(const int *, {T} *, const int *, {T} *, const int *,
    const {T} *);

static void run_one(int N, int iters, int warmup) {{
    int one = 1;
    {T} PARAM[5] = {{ {p7}, {p7}, {p7}, {p7}, {p7} }};
    PARAM[0] = Tr_from_d(-1.0); /* hflag=-1 → full matrix path */
    {T} *X = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Y = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Xi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    {T} *Yi = ({T} *)perf_aligned_alloc(64, (size_t)N * sizeof({T}));
    for (int i = 0; i < N; ++i) {{ int s = 0; Xi[i] = {fill}; }}
    for (int i = 0; i < N; ++i) {{ int s = 1; Yi[i] = {fill}; }}
    memcpy(X, Xi, (size_t)N * sizeof({T}));
    memcpy(Y, Yi, (size_t)N * sizeof({T}));
    for (int r = 0; r < warmup; ++r) {{
        {name}_(&N, X, &one, Y, &one, PARAM);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
        {name}_migrated_(&N, X, &one, Y, &one, PARAM);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    /* Per-call kernel-only timing — keep memcpy resets out of the
     * timed window so they don't Amdahl-mask MT scaling. */
    double t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_(&N, X, &one, Y, &one, PARAM);
        double b = perf_now_s();
        t_sum += (b - a);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    double t_subject = t_sum / (iters ? iters : 1);

    t_sum = 0;
    for (int it = 0; it < iters; ++it) {{
        double a = perf_now_s();
        {name}_migrated_(&N, X, &one, Y, &one, PARAM);
        double b = perf_now_s();
        t_sum += (b - a);
        memcpy(X, Xi, (size_t)N * sizeof({T})); memcpy(Y, Yi, (size_t)N * sizeof({T}));
    }}
    double t_mg = t_sum / (iters ? iters : 1);
    double flops = 4.0 * (double)N;
    perf_emit("{name}", "-", N, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", N, iters, flops, t_subject, t_mg);
    free(X); free(Y); free(Xi); free(Yi);
}}

''' + emit_main_linear('run_one')

# -- L1 rotg / rotmg: scalar-only generators. Bench loop length is the
# effective N; we measure per-call latency.


def emit_cabs1(name: str, ti: TypeInfo) -> str:
    """cabs1: scalar |Re(z)| + |Im(z)| (complex in, real out). No N — looped
    single-call shape like rotg; flops is a per-call proxy."""
    C = ti.cmplx_T
    R = ti.real_T
    return f'''
BLAS_EXTERN {R} {name}_(const {C} *);
BLAS_EXTERN {R} {name}_migrated_(const {C} *);

static void run_one(int iters, int warmup) {{
    {C} Z = {ti.cmplx_lit_p7};
    {R} acc = Tr_from_d(0.0);
    for (int r = 0; r < warmup; ++r) {{
        acc += {name}_(&Z);
        acc += {name}_migrated_(&Z);
    }}
    double t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) acc += {name}_(&Z);
    double t1 = perf_now_s();
    double t_subject = (t1 - t0) / (iters ? iters : 1);
    t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) acc += {name}_migrated_(&Z);
    t1 = perf_now_s();
    double t_mg = (t1 - t0) / (iters ? iters : 1);
    /* per-call proxy: 2 abs + 1 add */
    double flops = 3.0;
    perf_emit("{name}", "-", iters, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", iters, iters, flops, t_subject, t_mg);
    if ((double)(*((double*)&acc)) == -123e30) return;
}}

int main(void) {{
    int iters  = perf_env_int("BLAS_PERF_ITERS", 100000);
    int warmup = perf_env_int("BLAS_PERF_WARMUP", 1000);
    perf_print_header();
    run_one(iters, warmup);
    return 0;
}}
'''


def emit_rotg(name: str, ti: TypeInfo, is_c: bool) -> str:
    """rotg: real takes 4 scalar args; complex takes 4 scalars (C is real)."""
    Ta = ti.cmplx_T if is_c else ti.real_T
    Tc = ti.real_T  # c is always real
    Ts = Ta         # s matches A's type
    p7 = ti.cmplx_lit_p7 if is_c else ti.real_lit_p7
    return f'''
BLAS_EXTERN void {name}_({Ta} *, {Ta} *, {Tc} *, {Ts} *);
BLAS_EXTERN void {name}_migrated_({Ta} *, {Ta} *, {Tc} *, {Ts} *);

static void run_one(int iters, int warmup) {{
    {Ta} A = {p7}, B = {p7};
    {Tc} C = Tr_from_d(0.0);
    {Ts} S = {('Tc_from_d(0.0)' if is_c else 'Tr_from_d(0.0)')};
    /* per call: regenerate fresh A, B inputs */
    for (int r = 0; r < warmup; ++r) {{
        {Ta} a = A, b = B; {name}_(&a, &b, &C, &S);
        a = A; b = B; {name}_migrated_(&a, &b, &C, &S);
    }}
    double t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {{
        {Ta} a = A, b = B; {name}_(&a, &b, &C, &S);
    }}
    double t1 = perf_now_s();
    double t_subject = (t1 - t0) / (iters ? iters : 1);
    t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {{
        {Ta} a = A, b = B; {name}_migrated_(&a, &b, &C, &S);
    }}
    t1 = perf_now_s();
    double t_mg = (t1 - t0) / (iters ? iters : 1);
    /* report time per call as "flops" abuse: per-call flop count ~10. */
    double flops = 10.0;
    perf_emit("{name}", "-", iters, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", iters, iters, flops, t_subject, t_mg);
}}

int main(void) {{
    int iters  = perf_env_int("BLAS_PERF_ITERS", 100000);
    int warmup = perf_env_int("BLAS_PERF_WARMUP", 1000);
    perf_print_header();
    run_one(iters, warmup);
    return 0;
}}
'''


def emit_rotmg(name: str, ti: TypeInfo) -> str:
    T = ti.real_T
    p7 = ti.real_lit_p7
    return f'''
BLAS_EXTERN void {name}_({T} *, {T} *, {T} *, const {T} *, {T} *);
BLAS_EXTERN void {name}_migrated_({T} *, {T} *, {T} *, const {T} *, {T} *);

static void run_one(int iters, int warmup) {{
    {T} D1 = {p7}, D2 = {p7}, X1 = {p7}, Y1 = {p7};
    {T} PARAM[5];
    for (int r = 0; r < warmup; ++r) {{
        {T} d1 = D1, d2 = D2, x1 = X1;
        {name}_(&d1, &d2, &x1, &Y1, PARAM);
        d1 = D1; d2 = D2; x1 = X1;
        {name}_migrated_(&d1, &d2, &x1, &Y1, PARAM);
    }}
    double t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {{
        {T} d1 = D1, d2 = D2, x1 = X1;
        {name}_(&d1, &d2, &x1, &Y1, PARAM);
    }}
    double t1 = perf_now_s();
    double t_subject = (t1 - t0) / (iters ? iters : 1);
    t0 = perf_now_s();
    for (int it = 0; it < iters; ++it) {{
        {T} d1 = D1, d2 = D2, x1 = X1;
        {name}_migrated_(&d1, &d2, &x1, &Y1, PARAM);
    }}
    t1 = perf_now_s();
    double t_mg = (t1 - t0) / (iters ? iters : 1);
    double flops = 20.0;
    perf_emit("{name}", "-", iters, iters, flops, t_subject, t_mg);
    perf_emit_json("{name}", "-", iters, iters, flops, t_subject, t_mg);
}}

int main(void) {{
    int iters  = perf_env_int("BLAS_PERF_ITERS", 100000);
    int warmup = perf_env_int("BLAS_PERF_WARMUP", 1000);
    perf_print_header();
    run_one(iters, warmup);
    return 0;
}}
'''

